### ISSUE TITLE
Remove New React Lessons from C#| React Swap

### ISSUE THREAD

**Issue by vstankatz** [epicodus-curriculum/c-sharp-full-stack#1]
_This Issue is a duplicate made from the old epicodus-classroom page._ **Because this is a duplicate from the old repository all of the links cannot be directly used. Instead see what the name of the file is from the link and find it in the new file repo.**

Since we're moving the order or lessons following [this proposal](https://docs.google.com/document/d/1mh4VgrYReoIb0sXlAK6jAiirTjE_ElqPvJuKfI-g6kM/edit) React will be happening before C#. As a result lessons referring to things as upcoming in React, Career Services assignments, Whiteboarding, and Team Week should be updated or removed from C#.

### Whiteboarding Lessons (move)
- [x] [Whiteboard Practice #1](https://github.com/epicodus-classroom/c-sharp-curriculum/blob/main/3_database_basics/4b_classwork_whiteboard_practice_prime_checker_and_multiples.md) move from DB Basics to new Week 10 React lesson.
- [x] [Whiteboard Practice #2](https://github.com/epicodus-classroom/c-sharp-curriculum/blob/main/4_many_to_many_relationships/4a_whiteboarding_practice.md) move from Many-to-Many to new Week 11 React lesson.
- [x] [Whiteboard Practice #3](https://github.com/epicodus-classroom/c-sharp-curriculum/blob/main/5_authentication_with_identity/4a_whiteboarding_practice.md) move from Authentication with Identity to new Week 12 React lesson

### Career Services (move)

- [ ] [Agile Method](https://github.com/epicodus-classroom/c-sharp-curriculum/blob/main/1_test_driven_development_with_c/4c_shared_developer_reality_agile_methodology.md) move from C# TDD to Week 8 React.
- [ ] [Developer Meetups](https://github.com/epicodus-classroom/c-sharp-curriculum/blob/main/2_basic_web_apps/4c_shared_developer_reality_series_meetups.md) move from Basic C# Apps to Week 9 React lesson
- [ ] [Submitting Good Code](https://github.com/epicodus-classroom/c-sharp-curriculum/blob/main/3_database_basics/4b_shared_developer_reality_pull_requests_and_submitting_great_work.md) move from DB Basics to Week 10 React lesson
- [ ] [C# TDD Layout](https://github.com/epicodus-classroom/c-sharp-curriculum/blob/main/1_test_driven_development_with_c/layout.yaml) remove lines 58-83, lessons for a full Career Services day which should be moved to where resumes and cover letters happen in React.

### Team Week

- [ ] [C# Installation](https://github.com/epicodus-classroom/c-sharp-curriculum/blob/main/0a_getting_started_with_c/0b_classwork_c_installation_and_setup.md) lesson, update the line `Intermediate JavaScript team week,` to refer to React JavaScript Team Week.

### Layout Files
- All layout files need to be updated to remove lessons moved to React and vice versa

### Low Priority Updates

- [ ] [C# Curriculum Outline](https://github.com/epicodus-classroom/c-sharp-curriculum/blob/main/c-curriculum-org.md)
- [ ] [C# README](https://github.com/epicodus-classroom/c-sharp-curriculum/blob/main/README.md)

_Note to teachers: My computer had a blue screen of death today and I lost what I had previously written and tracked for this Issue so I'm saving it now and editing it as I go._

**Comment by vstankatz** [comment]
Remove references of React being something to learn in the future

### Basic Web Apps

- [ ] [How the Web Works](https://github.com/epicodus-classroom/c-sharp-curriculum/blob/main/2_basic_web_apps/0g_how_the_web_works_mvc_pattern.md) lesson, remove or update paragraph `But we'll also learn more about client-side architecture in our level three class when we study React. Like many JavaScript-powered website tools, React is client-side! This means we'll have plenty of experience with _both_ major web design paradigms before graduation.` so that React is talked about as something already known.

**Comment by vstankatz** [comment]
**These links will connect to the new repository**

### DEI Lessons (move?)
- [ ]  [Evening Course layout](https://github.com/epicodus-curriculum/c-sharp-full-stack/blob/main/layouts/course_evening_layout.yaml) lines 22-25, 51-54, & 75-78 link to Recognizing Privilege, Inclusive Terminology, and  Jokes and Appropriate Humor.
- [ ] [Course FT layout](https://github.com/epicodus-curriculum/c-sharp-full-stack/blob/main/layouts/course_ft_layout.yaml) lines 31-34, 60-63, & 84-87 link to Recognizing Privilege, Inclusive Terminology, and  Jokes and Appropriate Humor.
- [ ] [Course PT layout](https://github.com/epicodus-curriculum/c-sharp-full-stack/blob/main/layouts/course_pt_layout.yaml) lines 30-33, 59-62, & 83-86 link to Recognizing Privilege, Inclusive Terminology, and  Jokes and Appropriate Humor.
- [ ] [FT C# TDD layout](https://github.com/epicodus-curriculum/c-sharp-full-stack/blob/main/layouts/ft/ft_1_test-driven-development-with-c.yaml) lines 49-53 link to Recognizing Privilege.
- [ ]  [FT C# DB Basics layout](https://github.com/epicodus-curriculum/c-sharp-full-stack/blob/main/layouts/ft/ft_3_database-basics.yaml) lines 123-127 link to Inclusive Terminology.
- [ ] [FT C# Authentication with Identity](https://github.com/epicodus-curriculum/c-sharp-full-stack/blob/main/layouts/ft/ft_5_authentication-with-identity.yaml) lines 70-74 link to Jokes and Appropriate Humor.
- [ ] [PT C# TDD layout](https://github.com/epicodus-curriculum/c-sharp-full-stack/blob/main/layouts/pt/pt_2_test-driven-development-with-c-part-2.yaml) lines 24-28 link to Recognizing Privilege. 
- [ ]  [PTC# DB Basics layout](https://github.com/epicodus-curriculum/c-sharp-full-stack/blob/main/layouts/pt/pt_5_database-basics.yaml) lines 155-159 link to Inclusive Terminology.
- [ ] [PT C# Authentication with Identity](https://github.com/epicodus-curriculum/c-sharp-full-stack/blob/main/layouts/pt/pt_9_authentication-with-identity.yaml) lines 77-81 link to Jokes and Appropriate Humor.
